apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodb-ss.yaml
  - mongodb-svc.yaml

commonLabels:
  app: mongodb
  project: proj-gke

configMapGenerator:
  - name: mongodb-init-colordb
    files:
      - mongo-init.js
